// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXW01oibAzrRAMoymNKxBZt-lJ0W0LAeI',
    appId: '1:311761685163:web:5636fbe6a59c3f524d45ee',
    messagingSenderId: '311761685163',
    projectId: 'core-venturo-66c92',
    authDomain: 'core-venturo-66c92.firebaseapp.com',
    storageBucket: 'core-venturo-66c92.appspot.com',
    measurementId: 'G-9QP3CM4JLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbdGIWKiD8J-uslWsWzHI9qjtI7ngz7Q',
    appId: '1:311761685163:android:0803128f9768755e4d45ee',
    messagingSenderId: '311761685163',
    projectId: 'core-venturo-66c92',
    storageBucket: 'core-venturo-66c92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_O5ftwFAhcA2_dh-1cDpVxRpQK8wv_w',
    appId: '1:311761685163:ios:6e5dc04bb4cab62b4d45ee',
    messagingSenderId: '311761685163',
    projectId: 'core-venturo-66c92',
    storageBucket: 'core-venturo-66c92.appspot.com',
    iosClientId: '311761685163-kbgc020g07lhkttf3c7c29tkh1r5iruo.apps.googleusercontent.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_O5ftwFAhcA2_dh-1cDpVxRpQK8wv_w',
    appId: '1:311761685163:ios:6e5dc04bb4cab62b4d45ee',
    messagingSenderId: '311761685163',
    projectId: 'core-venturo-66c92',
    storageBucket: 'core-venturo-66c92.appspot.com',
    iosClientId: '311761685163-kbgc020g07lhkttf3c7c29tkh1r5iruo.apps.googleusercontent.com',
    iosBundleId: 'com.core.venturo',
  );
}
